#!/bin/sh

XMONAD_DIR=$HOME/.xmonad

xrdb -merge "$HOME/.Xresources"

# TODO: not sure if this is really needed... need to investigate
# recompile if broken shared libs after an upgrade
XMONAD_CUSTOM=$XMONAD_DIR/xmonad-$(uname -i)-linux
if [ -r $XMONAD_DIR/xmonad.hs -a -x $XMONAD_CUSTOM ]; then
  if ldd $XMONAD_CUSTOM | grep -q "not found"; then
    xmonad --recompile
  fi
fi

compton &
dunst &
polybar top &
feh --bg-scale --force-aliasing --randomize --no-fehbg "$HOME/.ncx/resources/wallpaper/pixel/plato_by_fool-d74d48d.png" &
exec /usr/bin/xmonad
