#!/bin/sh

XMONAD_DIR="$HOME/.xmonad"

xrdb -merge "$HOME/.Xresources"

# Shitty hack for setting DPI by passing an argument
# from the display manager.
if [ ! -z "$1" ]; then
  TMPFILE=$(mktemp)
  echo "! Fonts {{{
Xft.dpi: $1
! }}}" > "$TMPFILE"

  xrdb -merge "$TMPFILE"
  notify-send "Setting DPI to $1"
  rm -f "$TMPFILE"
fi

# Recompile xmonad config if an upgrade breaks shared libs
XMONAD_CUSTOM=$XMONAD_DIR/xmonad-$(uname -i)-linux
if [ -r $XMONAD_DIR/xmonad.hs -a -x $XMONAD_CUSTOM ]; then
  if ldd $XMONAD_CUSTOM | grep -q "not found"; then
    xmonad --recompile
  fi
fi

exec /usr/bin/xmonad
