#!/bin/sh


# set up a new system
install () {

}

# update existing system
update () {

}

# clean up silly oversights
fix() {
  echo "Fixing permissions"
  chmod a+rx *.sh
  chmod a+rx dotfiles/xmonad/.xmonad/*.sh
  chmod a+rx dotfiles/misc/.util/*
}

eval $1
