#!/bin/sh

. "./_.sh"

requireRoot

runScripts() {
  for INSTALLSCRIPT in "$NCXROOT/$1"_*.sh; do
    . "$INSTALLSCRIPT"
  done
}

fix() {
  echo "Fixing permissions - not maintained yet caveat emptor"
  chmod a+rx *.sh
  chmod a+rx dotfiles/xmonad/.xmonad/*.sh
  chmod a+rx dotfiles/utils/bin/*
}

help() {
  echo "Usage:

  ncx [option]

Options:

  install
    Set up a new system. Should generally only be run once.
    Can take quite some time.

  {up|update}
    Still deciding if this should git pull first or not
    Either way, run any non-install scripts (e.g. sync new dots)

  push
    Commit all changes and push to git remote

  fix
    Lazy sweeping fixes. Shouldn't need but, you know."

}

if [ $# -lt 1 ]; then
  help
  exit
fi

case $1 in
  up|update) runScripts sync;;
  install) runScripts install;;
  fix) fix;;
  *) help;;
esac
