#!/usr/bin/python3

# start in default .ncx dir

# Things to do:
#  Maintenance
#   fix permissions
#   update from git
#   push updates
#  Reinstall
#   remove itself
#   clone new copy
#   run installer
# install/update/push/fix

class fg:
    black='\033[30m'
    red='\033[31m'
    green='\033[32m'
    orange='\033[33m'
    blue='\033[34m'
    purple='\033[35m'
    cyan='\033[36m'
    lightgrey='\033[37m'
    darkgrey='\033[90m'
    lightred='\033[91m'
    lightgreen='\033[92m'
    yellow='\033[93m'
    lightblue='\033[94m'
    pink='\033[95m'
    lightcyan='\033[96m'
    white='\033[97m'
class bg:
    black='\033[40m'
    red='\033[41m'
    green='\033[42m'
    orange='\033[43m'
    blue='\033[44m'
    purple='\033[45m'
    cyan='\033[46m'
    lightgrey='\033[47m'
class text:
    reset='\033[0m'
    bold='\033[01m'
    disable='\033[02m'
    underline='\033[04m'
    reverse='\033[07m'
    strikethrough='\033[09m'
    invisible='\033[08m'

import sys,re
import json
import urllib3
import subprocess

# setup / bootstrap options

def install(args):
  print(f"Installing: {fg.white}{args[0]}{text.reset}")

def sync(args):
  print("Syncing settings...")

# utils

def wifi(args):
    subprocess.call('nmcli', 'd w')

def backlight(args):

    # TODO: make configurable on setup
    backlight_value = '/sys/class/backlight/intel_backlight/brightness'

    if(len(args) == 0):
        brightness = open(backlight_maxvalue, "r").read()
        print(f"Current backlight value: {brightness} / {get_backlight_max()}")
        return

    if(args[0] == 'max'):
        print('Setting to max')
        return

    if(args[0] == 'min'):
        print('Setting to min')
        return

    if(args[0] in ['+','-']):
        operator = args[:1]
        arg=args[1:]
        print('Setting to x')
        return

    print(f"Setting value to: {args[0]}")
    #subprocess.call('xbacklight' '-?')
    return

def get_backlight_max():
    # TODO: make configurable on setup
    backlight_maxvalue = '/sys/class/backlight/intel_backlight/max_brightness'
    return open(backlight_maxvalue, "r").read()

# misc

def help(args):
    print(f"Usage: etc" )

if len(sys.argv) == 1:
    help()
    exit(0)

valid_actions = ['install','sync','help','version', 'wifi', 'backlight']
cmdargs = list(sys.argv)
cmdargs.pop(0)
action = cmdargs.pop(0)

if action in valid_actions:
    eval(action + "(cmdargs)")
    exit(0)

print("Invalid action: " + action)
help()
exit(0)
